[package]
name = "rust-sled-crud-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = "4.5.13"
serde = { version = "1.0.204", features = ["derive"]}
serde_derive = "1.0.204"
sled = "0.34.7"
uuid = {version="1.10.0", features = ["serde"]}
